module DecoupageAdministratif
  module BaseModel
    def find_by: (Hash[Symbol, untyped]) -> untyped
    def where: (Hash[Symbol, untyped]) -> Array[untyped]
    def where_ilike: (Hash[Symbol, String]) -> Array[untyped]
  end
end
