module DecoupageAdministratif
  module BaseModel
    def find: (String) -> untyped
    def find_by: (Hash[Symbol, untyped]) -> untyped
    def where: (Hash[Symbol, untyped]) -> Array[untyped]
  end
end
