module DecoupageAdministratif
  class Epci
    extend BaseModel
    attr_reader code: String
    attr_reader nom: String
    attr_reader membres: Array[{ code: String, nom: String }]

    def initialize: (
        code: String,
        nom: String,
        membres: Array[{ code: String, nom: String }]
      ) -> void

    def self.all: () -> Array[Epci]

    def self.search_by_communes_codes: (Array[String]) -> Array[Epci]

    def communes: () -> Array[Commune]

    def regions: () -> Array[Region]
  end
end
