module DecoupageAdministratif
  module TerritoryStrategies
    class Base
      def initialize: (untyped territory) -> void

      def includes_any_commune_code?: (Array[String] commune_insee_codes) -> bool

      def insee_codes: () -> Array[String]

      private

      attr_reader territory: untyped

      def check_inclusion: (Array[String] commune_insee_codes) -> bool

      def calculate_insee_codes: () -> Array[String]
    end

    class CommuneStrategy < Base
      private

      def check_inclusion: (Array[String] commune_insee_codes) -> bool

      def calculate_insee_codes: () -> Array[String]
    end

    class DepartementStrategy < Base
      private

      def check_inclusion: (Array[String] commune_insee_codes) -> bool

      def calculate_insee_codes: () -> Array[String]
    end

    class RegionStrategy < Base
      private

      def check_inclusion: (Array[String] commune_insee_codes) -> bool

      def calculate_insee_codes: () -> Array[String]
    end

    class EpciStrategy < Base
      private

      def check_inclusion: (Array[String] commune_insee_codes) -> bool

      def calculate_insee_codes: () -> Array[String]
    end
  end
end