module DecoupageAdministratif
  module TerritoryExtensions
    def includes_any_commune_code?: (Array[String] commune_insee_codes) -> bool

    def territory_insee_codes: () -> Array[String]

    private

    def territory_strategy: () -> TerritoryStrategies::Base
  end
end